### PR TITLE
STUD-935 Add Workiva CI

### PR DESCRIPTION
**Pull request by joewaters-wf**
## Ticket

https://jira.atl.workiva.net/browse/STUD-803

Sets up Basic Workiva CI processes
- Dockerfile
- skynet.yaml
- dependabot
- aviary

## QA
- [x] Build artifacts contain: 
    - [x] .jar
    - [x] sources.jar
    - [x] javadoc.jar
- [x] Package appears on `maven-dev-internal` in Artifactory ([Link to artifactory](https://workivaeast.jfrog.io/ui/packages/gav:%2F%2Fcom.jcraft:jsch?name=jsch&type=packages))
- [x] Skynet results show same number of tests as previous CI runner (There are no tests in this repo, [ticket created for testing](https://jira.atl.workiva.net/browse/STUD-1122))

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(2) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
<li>Watched keyword <code>BUILD_ARTIFACTS_VERACODE</code> in <code>Dockerfile</code> line(s) ['24'] added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by andrewunderwood-wf** [comment]
At some point we should alter [this line](https://github.com/Workiva/jsch/blob/0.1.57/src/main/java/com/jcraft/jsch/JSch.java#L39) so that the `VERSION` static is derived from the manifest file.  However, that change is beyond the scope of this PR.

https://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code

**Review by andrewunderwood-wf — APPROVED** [review]

**Comment by jimgriffith-wk** [comment]
QA +1
Confirmed artifacts exist and were published, and that the testing ticket exists.

**Comment by joewaters-wf** [comment]
@Workiva/release-management-p for merge

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
