### PR TITLE
RM-148885 Release 0.1.58

### PR DESCRIPTION
**Pull request by joewaters-wf**
## Release PR

Release PR Contains:
- https://github.com/Workiva/jsch/pull/1

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(2) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
<li>Watched keyword <code>BUILD_ARTIFACTS_VERACODE</code> in <code>Dockerfile</code> line(s) ['24'] added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by jimgriffith-wk — APPROVED** [review]

**Comment by jimgriffith-wk** [comment]
QA +1

**Comment by joewaters-wf** [comment]
@Workiva/release-management-p for merge

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
